#!/usr/bin/env python
import requests
import digitalio
import sys
import Adafruit_DHT
import board
import RPi.GPIO as GPIO
from mfrc522 import SimpleMFRC522
import time
url = 'https://rasp-rfid.azurewebsites.net/api/HttpTrigger2?'

reader = SimpleMFRC522()
ledZielone = digitalio.DigitalInOut(board.D13)
ledZielone.direction = digitalio.Direction.OUTPUT
ledCzerwone = digitalio.DigitalInOut(board.D6)
ledCzerwone.direction = digitalio.Direction.OUTPUT
ledZolte = digitalio.DigitalInOut(board.D15)
LedZolte.direction = digitalio.Direction.OUTPUT

try:
    id, text = reader.read()
    print(id)
    print(text)
    id = str(id)
    humidity, temperature = Adafruit_DHT.read_retry(11, 4)
    myobj = {"Nr_karty": id}
    req = requests.post(url, json=myobj)
    ledZolte.value = True
    print(req.status_code)
    print('Temp: {0:0.1f} C  Humidity: {1:0.1f} %'.format(temperature, humidity))
    if(req.status_code == 202):
        ledZolte.value = False
        ledZielone.value = True
        time.sleep(4)
        ledZielone.value = False
       
    else:
        ledZolte.value = False
        ledCzerwone.value = True
        time.sleep(4)
        ledCzerwone.value = False
        
finally:
    GPIO.cleanup()
